-- Seed cms_pages.blocks with default marketing content (mirrors src/data/cms-defaults.ts).
-- Safe to re-run: overwrites blocks and updated_at for each slug.

UPDATE public.cms_pages
SET
  blocks = $cms_landing$[{"type":"heading","level":6,"text":"Now onboarding founding stallions – registry visibility ahead of full launch."},{"type":"heading","level":1,"text":"Performance Stallion Breeding Registry"},{"type":"text","text":"Pedigree | Performance | Breeding Information"},{"type":"text","text":"Leading Sires is a performance-focused sire registry created for breeders and horsemen who value proven working genetics."},{"type":"text","text":"Quarter Horses | Paints | Appaloosas"},{"type":"buttons","items":[{"label":"Stallion Directory","href":"/stallions","variant":"primary"},{"label":"Submit a Listing","href":"/submit-stallion/before-submit","variant":"secondary"}]},{"type":"grid","columns":2,"cells":[[{"type":"heading","level":2,"text":"Transparency & Verification"},{"type":"text","text":"Each stallion is presented on a single reference page that consolidates pedigree, performance and breeding information, supported by official association records and ranch or farm websites."}],[{"type":"heading","level":2,"text":"Independent Reference"},{"type":"text","text":"Leading Sires is an independent reference platform, not a marketplace. We exist to provide clear and accessible information for breeders and horsemen across international borders."}]]},{"type":"heading","level":2,"text":"Built for the Western Performance Industry"},{"type":"text","text":"Our registry supports owners and farms across Australia, New Zealand, Canada, North and South America, and Europe. By centralizing verifiable data, we reduce administrative burden and contribute to industry sustainability."},{"type":"button","label":"Learn more about the registry →","href":"/about","variant":"secondary"}]$cms_landing$::jsonb,
  updated_at = now()
WHERE slug = 'landing';

UPDATE public.cms_pages
SET
  blocks = $cms_about$[{"type":"heading","level":1,"text":"About the Leading Sires Registry","align":"center"},{"type":"text","align":"center","text":"Leading Sires Registry is an independent, performance-focused reference created for breeders and horsemen who value proven working genetics over marketing, built to function across international borders.\n\nThe registry provides a single, seasonally updated reference page per stallion, consolidating publicly available performance, pedigree, and breeding information, alongside stud-provided details. Each listing links directly back to the official breed association and the stallion's home stud or ranch, ensuring the information remains transparent and verifiable.\n\nLeading Sires is not a stud book, association or marketplace. It does not replace any existing breed or discipline registers. Instead, it exists to reduce administrative burden for stallion owners, provide clear and accessible information for breeders, and contribute positively to the sustainability and transparency of the western performance horse industry."},{"type":"grid","columns":2,"cells":[[{"type":"heading","level":2,"text":"Pedigree and Historical Records"},{"type":"text","text":"The registry preserves pedigree and lineage information for stallions regardless of current standing status. Deceased stallions and historically significant sires may be included for pedigree reference and research purposes.\n\nWhere a stallion is no longer standing or ownership information is incomplete, records are presented in a factual, non-speculative manner."}],[{"type":"heading","level":2,"text":"International Scope"},{"type":"text","text":"The Leading Sires Registry support owners and farms across Australia, New Zealand, Canada, North and South America and Europe.\n\nListings are presented in a consistent, non-commercial format and link back to official association records and stud or distributor websites in their original language, allowing breeders to access reliable information across jurisdictions."}],[{"type":"heading","level":2,"text":"Independence of the Registry"},{"type":"text","text":"Inclusion of an owner or stallion profile does not imply endorsement, recommendation, or commercial partnership. The Leading Sires Registry functions as an independent reference platform, not a marketing service."}],[{"type":"heading","level":2,"text":"Updates and Changes"},{"type":"text","text":"Ownership, standing status, and service arrangements may change over time. Where possible, historical changes are recorded to maintain the integrity of the registry.\n\nOwners and authorised representatives are encouraged to keep information current for active records."}]]},{"type":"buttons","items":[{"label":"Stallion Directory","href":"/stallions","variant":"secondary"},{"label":"Submit a Stallion Listing","href":"/submit-stallion/before-submit","variant":"secondary"}]}]$cms_about$::jsonb,
  updated_at = now()
WHERE slug = 'about';

UPDATE public.cms_pages
SET
  blocks = $cms_pricing$[{"type":"heading","level":1,"text":"Pricing","align":"center"},{"type":"text","align":"center","text":"The Leading Sires Registry is an independent global reference, not a marketplace. Listings are presented in a consistent, non commercial format and are not ranked, promoted, or prioritised."},{"type":"heading","level":2,"text":"Stallion Listings"},{"type":"text","text":"Farm/Ranch Registry Account – 79 per year\n\n(USD/EUR/AUD/CAD/NZD – billed in your selected country)\n\n• Unlimited stallion profiles under one farm or ranch\n• Standardised stallion pages with verified registry links\n• Genetics, breeding information, media and service provider links\n• Updates managed annually or as required\n• No advertising, no featured placements, no performance rankings"},{"type":"heading","level":2,"text":"Pedigree-Only & Historical Listings"},{"type":"text","text":"Pedigree and lineage records may be included at no cost where a stallion is:\n\n• deceased\n• no longer standing\n• of historical or breeding significance only\n\nThese records are presented for reference and research purposes and do not imply current availability or commercial activity."},{"type":"heading","level":2,"text":"International Listings & Currency"},{"type":"text","text":"The Leading Sires Registry supports listings across:\n\n• Australia\n• New Zealand\n• Canada\n• North & South America\n• Europe"},{"type":"heading","level":2,"text":"Important Notes"},{"type":"text","text":"• The Leading Sires Registry is not a stud book, association or marketplace.\n• Listings are factual and reference based."}]$cms_pricing$::jsonb,
  updated_at = now()
WHERE slug = 'pricing';
